const express = require('express');
const app = express();
const port = 3000;

app.set('view engine', 'ejs');
app.use(express.static('public'));

app.get('/', (req, res) => {//controller/rota
  res.render('index', { message: 'Rodando index' });
});

const produtos =[
  {id: 1, titulo: "Chuck Taylor All Star Seasonal Colors Verde", preco:"R$ 269,90", descricao: "Criado em 1917 como um Tênis de basquete que não escorregava, o All Star foi originalmente promovido pela performance do jogador Chuck Taylor. Porém, ao passar das décadas algo incrível acontece: o sneaker, com seu visual atemporal e seu clássico logo no tornozelo, foi organicamente adotado por rebeldes, artistas, músicos, sonhadores, pensadores e originais. Sua silhueta clássica, o Chuck Taylor All Star está entre os modelos de sneakers mais icônicos de todos os tempos um símbolo de conforto e autenticidade cultural.", imagem:"Chuck Taylor All Star Seasonal Colors Verde.jpg"},
  {id: 2, titulo: "Chuck 70 Seasonal Colors Azul", preco:"R$ 429,90", descricao: "Criado em 1917 como um Tênis de basquete que não escorregava, o All Star foi originalmente promovido pela performance do jogador Chuck Taylor. Porém, ao passar das décadas algo incrível acontece: o sneaker, com seu visual atemporal e seu clássico logo no tornozelo, foi organicamente adotado por rebeldes, artistas, músicos, sonhadores, pensadores e originais. Sua silhueta clássica, o Chuck Taylor All Star está entre os modelos de sneakers mais icônicos de todos os tempos um símbolo de conforto e autenticidade cultural.", imagem:"Run Star Hike Seasonal Colors Verde.jpg"},
  {id: 3, titulo: "Run Star Hike Seasonal Colors Verde", preco:"R$ 529,90", descricao: "Criado em 1917 como um Tênis de basquete que não escorregava, o All Star foi originalmente promovido pela performance do jogador Chuck Taylor. Porém, ao passar das décadas algo incrível acontece: o sneaker, com seu visual atemporal e seu clássico logo no tornozelo, foi organicamente adotado por rebeldes, artistas, músicos, sonhadores, pensadores e originais. Sua silhueta clássica, o Chuck Taylor All Star está entre os modelos de sneakers mais icônicos de todos os tempos um símbolo de conforto e autenticidade cultural.", imagem:"Chuck 70 Seasonal Colors Azul.jpg"},
  {id: 4, titulo: "Chuck 70 Plus Preto", preco:"R$ 579,90", descricao: "Criado em 1917 como um Tênis de basquete que não escorregava, o All Star foi originalmente promovido pela performance do jogador Chuck Taylor. Porém, ao passar das décadas algo incrível acontece: o sneaker, com seu visual atemporal e seu clássico logo no tornozelo, foi organicamente adotado por rebeldes, artistas, músicos, sonhadores, pensadores e originais. Sua silhueta clássica, o Chuck Taylor All Star está entre os modelos de sneakers mais icônicos de todos os tempos um símbolo de conforto e autenticidade cultural.", imagem:"Chuck 70 Plus Preto.jpg"},
  {id: 5, titulo: "Chuck 70 Prism Glitter Amarelo", preco:"R$ 549,90", descricao: "Criado em 1917 como um Tênis de basquete que não escorregava, o All Star foi originalmente promovido pela performance do jogador Chuck Taylor. Porém, ao passar das décadas algo incrível acontece: o sneaker, com seu visual atemporal e seu clássico logo no tornozelo, foi organicamente adotado por rebeldes, artistas, músicos, sonhadores, pensadores e originais. Sua silhueta clássica, o Chuck Taylor All Star está entre os modelos de sneakers mais icônicos de todos os tempos um símbolo de conforto e autenticidade cultural.", imagem:"Chuck 70 Prism Glitter Amarelo.jpg"},
  {id: 6, titulo: "Chuck Taylor All Star Seasonal Colors Verde Cano baixo", preco:"R$ 249,90", descricao: "Criado em 1917 como um Tênis de basquete que não escorregava, o All Star foi originalmente promovido pela performance do jogador Chuck Taylor. Porém, ao passar das décadas algo incrível acontece: o sneaker, com seu visual atemporal e seu clássico logo no tornozelo, foi organicamente adotado por rebeldes, artistas, músicos, sonhadores, pensadores e originais. Sua silhueta clássica, o Chuck Taylor All Star está entre os modelos de sneakers mais icônicos de todos os tempos um símbolo de conforto e autenticidade cultural.", imagem:"Chuck Taylor All Star Seasonal Colors Verde cano baixo.jpg"},
  {id: 7, titulo: "Chuck 70 Plus Pride Branco", preco:"R$ 649,90", descricao: "Criado em 1917 como um Tênis de basquete que não escorregava, o All Star foi originalmente promovido pela performance do jogador Chuck Taylor. Porém, ao passar das décadas algo incrível acontece: o sneaker, com seu visual atemporal e seu clássico logo no tornozelo, foi organicamente adotado por rebeldes, artistas, músicos, sonhadores, pensadores e originais. Sua silhueta clássica, o Chuck Taylor All Star está entre os modelos de sneakers mais icônicos de todos os tempos um símbolo de conforto e autenticidade cultural.", imagem:"Chuck 70 Plus Pride Branco.jpg"},
  {id: 8, titulo: "Chuck Taylor All Star Preto", preco:"R$ 259,90", descricao: "Criado em 1917 como um Tênis de basquete que não escorregava, o All Star foi originalmente promovido pela performance do jogador Chuck Taylor. Porém, ao passar das décadas algo incrível acontece: o sneaker, com seu visual atemporal e seu clássico logo no tornozelo, foi organicamente adotado por rebeldes, artistas, músicos, sonhadores, pensadores e originais. Sua silhueta clássica, o Chuck Taylor All Star está entre os modelos de sneakers mais icônicos de todos os tempos um símbolo de conforto e autenticidade cultural.", imagem:"Chuck Taylor All Star Preto.jpg"},
  {id: 9, titulo: "Chuck Taylor All Star Fairy Goddess Preto", preco:"R$ 399,90", descricao: "Criado em 1917 como um Tênis de basquete que não escorregava, o All Star foi originalmente promovido pela performance do jogador Chuck Taylor. Porém, ao passar das décadas algo incrível acontece: o sneaker, com seu visual atemporal e seu clássico logo no tornozelo, foi organicamente adotado por rebeldes, artistas, músicos, sonhadores, pensadores e originais. Sua silhueta clássica, o Chuck Taylor All Star está entre os modelos de sneakers mais icônicos de todos os tempos um símbolo de conforto e autenticidade cultural.", imagem:"Chuck Taylor All Star Fairy Goddess Preto.jpg"},
  {id: 10, titulo: "Chuck Taylor All Star City Utility Preto", preco:"R$ 529,90", descricao: "Criado em 1917 como um Tênis de basquete que não escorregava, o All Star foi originalmente promovido pela performance do jogador Chuck Taylor. Porém, ao passar das décadas algo incrível acontece: o sneaker, com seu visual atemporal e seu clássico logo no tornozelo, foi organicamente adotado por rebeldes, artistas, músicos, sonhadores, pensadores e originais. Sua silhueta clássica, o Chuck Taylor All Star está entre os modelos de sneakers mais icônicos de todos os tempos um símbolo de conforto e autenticidade cultural.", imagem:"Chuck Taylor All Star City Utility Preto.jpg"}
]

app.get('/produto', (req, res) => {
  res.render('produto', { message: 'Rodando produto' });
});

app.listen(port, () => {
  console.log(`Servidor rodando em http://localhost:${port}`);
});